version: '{branch}-{build}'
clone_folder: c:\projects\asynqro

matrix:
  fast_finish: true

image:
- Visual Studio 2019

configuration:
- Release

platform:
- x64

environment:
  matrix:
    - with_qt: ON
    - with_qt: OFF

skip_commits:
  files:
    - benchmarks/
    - docker/
    - .ci/conan/
    - conan_tests/
    - .travis.yml
    - conanfile.py
    - README.md
    - LICENSE
    - .gitignore
    - .clang-format

init:
- set QTDIR=C:/Qt/nonexistent/msvc2017_64
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
    set generator="Visual Studio 16 2019" &&
    if "%with_qt%"=="ON" (
      set "QTDIR=C:/Qt/5.14/msvc2017_64" &&
      set "prefix_path=%QTDIR%"
    )
  )
- set PATH=C:\projects\asynqro\build\%CONFIGURATION%;%QTDIR%/bin;%PATH%
- echo %PATH%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake -DCMAKE_PREFIX_PATH=%prefix_path% -DASYNQRO_BUILD_TESTS=ON -DASYNQRO_QT_SUPPORT=%with_qt% .. -G %generator% -A x64

build:
  project: c:\projects\asynqro\build\asynqro.sln
  verbosity: minimal
  parallel: true
test_script:
- echo "Skipping testing on Appveyor (check travis for tests)"
